# -*- coding: utf-8 -*-
"""Step 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Pon-s_evfMk90JqDK_-dJqcB9EJPrz-
"""

print("H A N G M A N")
print("The game will be available soon.")