# -*- coding: utf-8 -*-
"""Step 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Pon-s_evfMk90JqDK_-dJqcB9EJPrz-
"""

a = input()
b = [[a[0], a[1], a[2]], [a[3], a[4], a[5]], [a[6], a[7], a[8]]]
print(f'''---------
| {b[0][0]} {b[0][1]} {b[0][2]} |
| {b[1][0]} {b[1][1]} {b[1][2]} |
| {b[2][0]} {b[2][1]} {b[2][2]} |
---------''')
X = 0
O = 0
for i in b:
    for c in i:
        if c == 'X':
            X +=1
        elif c == 'O':
            O +=1
xwins = 0
owins = 0
if b[1][1] == b[0][0] == b[2][2] == 'X' or b[0][2] == b[1][1] == b[2][0] == 'X':
    xwins += 1
elif b[1][1] == b[0][0] == b[2][2] == 'X' or b[0][2] == b[1][1] == b[2][0] == 'O':
    owins += 1
else:
    for i in range(3):
        if b[i][0] == b[i][1] == b[i][2] == 'X' or b[0][i] == b[1][i] == b[2][i] == 'X':
            xwins += 1
        elif b[i][0] == b[i][1] == b[i][2] == 'X' or b[0][i] == b[1][i] == b[2][i] == 'O':
            owins += 1
if abs(X - O) >= 2:
    print('Impossible')
elif xwins and owins:
    print('Impossible')
elif xwins:
    print('X wins')
elif owins:
    print('O wins')
elif not xwins and not owins and X + O == 9:
    print('Draw')
elif not xwins and not owins and X + O < 9:
    print('Game not finished')