# -*- coding: utf-8 -*-
"""Step 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Pon-s_evfMk90JqDK_-dJqcB9EJPrz-
"""

symbols = str(input())
print("---------")
print("|", symbols[0], symbols[1], symbols[2], "|")
print("|", symbols[3], symbols[4], symbols[5], "|")
print("|", symbols[6], symbols[7], symbols[8], "|")
print("---------")